### ISSUE TITLE
Категории

### ISSUE THREAD

**Issue by Kirrrusha** [theyurec/project-shop#13]
Делаем через статический config, кнопка Все категории ведёт на роут Категории
<img width="274" alt="image" src="https://user-images.githubusercontent.com/19910108/178663033-510edcf8-a1d7-4707-af2a-012bb6edc212.png">

**Comment by Kirrrusha** [comment]
Реализуем, как отдельный компонент в разделе components и импортируем на страницу Main Page

**Comment by Kirrrusha** [comment]
Компонент реализуем для десктопной и мобильной версии

**Comment by theyurec** [comment]
done
