### ISSUE TITLE
Слайдер товаров

### ISSUE THREAD

**Issue by Kirrrusha** [theyurec/project-shop#14]
Реализуем через статический конфиг, отдельным компонентом, потом импортируем в MainPage

<img width="288" alt="image" src="https://user-images.githubusercontent.com/19910108/178663349-1f592ce5-d008-47d8-be86-1a248eeb9a9c.png">

**Comment by Kirrrusha** [comment]
Компонент реализуем для десктопной и мобильной версии

**Comment by theyurec** [comment]
done
