### ISSUE TITLE
Форма обратной связи

### ISSUE THREAD

**Issue by Kirrrusha** [theyurec/project-shop#15]
Реализуем отдельным компонентом, импортим на MainPage
<img width="308" alt="image" src="https://user-images.githubusercontent.com/19910108/178663499-a65f2512-0a24-4a1d-8d3d-10b53d8b4004.png">

**Comment by Kirrrusha** [comment]
Компонент реализуем для десктопной и мобильной версии

**Comment by theyurec** [comment]
done
