### ISSUE TITLE
Мобильная версия Header

### ISSUE THREAD

**Issue by Kirrrusha** [theyurec/project-shop#16]
Закрытый бургер
https://www.figma.com/file/F3hGqySdYVV2jb2WedyMAE/%D0%9C%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-%D0%B7%D0%B0%D0%BC%D0%BA%D0%BE%D0%B2?node-id=62%3A1309

Открытый бургер
https://www.figma.com/file/F3hGqySdYVV2jb2WedyMAE/%D0%9C%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-%D0%B7%D0%B0%D0%BC%D0%BA%D0%BE%D0%B2?node-id=117%3A4165

**Comment by theyurec** [comment]
done
