### ISSUE TITLE
Вёрстка страницы Categories

### ISSUE THREAD

**Issue by Kirrrusha** [theyurec/project-shop#22]
Десктоп
https://www.figma.com/file/F3hGqySdYVV2jb2WedyMAE/%D0%9C%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-%D0%B7%D0%B0%D0%BC%D0%BA%D0%BE%D0%B2?node-id=41%3A900

Мобайл
https://www.figma.com/file/F3hGqySdYVV2jb2WedyMAE/%D0%9C%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-%D0%B7%D0%B0%D0%BC%D0%BA%D0%BE%D0%B2?node-id=115%3A1480

Роут `path="/categories"`

**Comment by theyurec** [comment]
done
